spring:
  driver-class-name: com.mysql.jdbc.Driver
  datasource:
    url: jdbc:mysql://spa-mysql:3306/spa
    username: SPA_USER
    password: SPA_PASSWORD

server:
  port: 8888

spa:
  security:
    username: spa_user
    password: spa_pass
    role: ADMIN
